main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("teas/", views.teas_index, name="index"),
    path("teas/<int:tea_id>/", views.teas_detail, name="detail"),
    path("teas/create/", views.TeaCreate.as_view(), name="teas_create"),
    path("cats/<int:pk>/update/", views.TeaUpdate.as_view(), name="teas_update"),
    path("cats/<int:pk>/delete/", views.TeaDelete.as_view(), name="teas_delete"),
    path(
        "teas/<int:tea_id>/add_sweetening/", views.add_sweetening, name="add_sweetening"
    ),
    path(
        "teas/<int:tea_id>/assoc_cup/<int:cup_id>/", views.assoc_cup, name="assoc_cup"
    ),
    path("cups/", views.CupList.as_view(), name="cups_index"),
    path("cups/<int:pk>/", views.CupDetail.as_view(), name="cups_detail"),
    path("cups/create/", views.CupCreate.as_view(), name="cups_create"),
    path("cups/<int:pk>/update/", views.CupUpdate.as_view(), name="cups_update"),
    path("cups/<int:pk>/delete/", views.CupDelete.as_view(), name="cups_delete"),
    path("accounts/signup/", views.signup, name="signup"),
]

teacollector/urls.py
from django.contrib import admin

# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    # In this case '' represents the root route
    path("", include("main_app.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

STYLES = (
    ("P", "Plain"),
    ("S", "Sugar"),
    ("A", "Almond Milk & Sugar"),
    ("M", "Soy Milk & Sugar"),
)

# Create your models here.
class Cup(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("cups_detail", kwargs={"pk": self.id})


class Tea(models.Model):
    name = models.CharField(max_length=100)
    kind = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    cups = models.ManyToManyField(Cup)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail", kwargs={"tea_id": self.id})

    class Meta:
        ordering = ["id"]


class Sweetening(models.Model):
    date = models.DateField("Tea time")
    style = models.CharField(
        max_length=1,
        # add the 'choices' field option
        choices=STYLES,
        # set the default value for style to 'P'
        default=STYLES[0][0],
    )

    # FOREIGN KEY
    tea = models.ForeignKey(Tea, on_delete=models.CASCADE)

    def __str__(self):
        # friendly value of Field.choice
        return f"{self.get_style_display()} on {self.date}"

    class Meta:
        ordering = ["-date"]

main_app/forms.py
from django.forms import ModelForm
from .models import Sweetening


class SweeteningForm(ModelForm):
    class Meta:
        model = Sweetening
        fields = ["date", "style"]

main_app/views.py
from .models import Tea, Cup
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import SweeteningForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.

# define the home view
def home(request):
    return render(request, "home.html")


def about(request):
    return render(request, "about.html")

@login_required
def teas_index(request):
    teas = Tea.objects.filter(user=request.user)
    return render(request, "teas/index.html", {"teas": teas})

@login_required
def teas_detail(request, tea_id):
    tea = Tea.objects.get(id=tea_id)
    # render to template
    sweetening_form = SweeteningForm()
    cups_tea_doesnt_have = Cup.objects.exclude(id__in=tea.cups.all().values_list("id"))
    return render(
        request,
        "teas/detail.html",
        {"tea": tea, "sweetening_form": sweetening_form, "cups": cups_tea_doesnt_have},
    )

@login_required
def assoc_cup(request, tea_id, cup_id):
    Tea.objects.get(id=tea_id).cups.add(cup_id)
    return redirect("detail", tea_id=tea_id)

@login_required
def add_sweetening(request, tea_id):
    # create a ModelForm instance using the data in request.POST
    form = SweeteningForm(request.POST)
    # validate the form
    if form.is_valid():
        #  don't save the form to the db until it
        # has the tea_id assigned
        new_sweetening = form.save(commit=False)
        new_sweetening.tea_id = tea_id
        new_sweetening.save()
    return redirect("detail", tea_id=tea_id)


class TeaCreate(LoginRequiredMixin, CreateView):
    model = Tea
    fields = "__all__"
    success_url = "/teas/"

    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the cat
        # Let the CreateView do its job as usual
        return super().form_valid(form)


class TeaUpdate(LoginRequiredMixin, UpdateView):
    model = Tea
    fields = "__all__"


class TeaDelete(LoginRequiredMixin, DeleteView):
    model = Tea
    success_url = "/teas/"


class CupList(LoginRequiredMixin, ListView):
    model = Cup


class CupDetail(LoginRequiredMixin, DetailView):
    model = Cup


class CupCreate(LoginRequiredMixin, CreateView):
    model = Cup
    fields = "__all__"


class CupUpdate(LoginRequiredMixin, UpdateView):
    model = Cup
    fields = ["name", "color"]


class CupDelete(LoginRequiredMixin, DeleteView):
    model = Cup
    success_url = "/cups/"


def signup(request):
    error_message = ""
    if request.method == "POST":
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect("index")
        else:
            error_message = "Invalid sign up - try again"
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "registration/signup.html", context)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Tea Collector</h1>
<hr />
<p>Hire the Tea Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Tea Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper teal">
          <ul>
            <li>
              <a href="/" class="left brand-logo">&nbsp;&nbsp;TeaCollector</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'cups_create' %}">Add a Cup</a></li>
            <li><a href="{% url 'cups_index' %}">View All Cups</a></li>
            <li><a href="{% url 'teas_create' %}">Add a Tea</a></li>
            <li><a href="{% url 'index' %}">View All My Teas</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer teal">
      <div class="right">
        All Rights Reserved, &copy; 2021 Tea Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/cup_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Cup</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'cups_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/cup_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Cup Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cup.name }}</span>
        <p>Color: {{ cup.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'cups_update' cup.id %}">Edit</a>
        <a href="{% url 'cups_delete' cup.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/cup_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Cup</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/cup_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Cup List</h1>

{% for cup in cup_list %}
  <a href="{% url 'cups_detail' cup.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ cup.name }}</span>
            <p>Color: {{ cup.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/tea_confirm_delete.html
{% extends 'base.html' %} 
{% block content %}
<h1>Delete Tea</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' tea.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/tea_form.html
{% extends 'base.html' %} 
{% block content %} 
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
    <h1>Add Tea</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn brown darken-2" />
</form>
{% endblock %}

main_app/templates/teas/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Tea Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ tea.name }}</span>
        <p>Type: {{ tea.type }}</p>
        <p>Description: {{ tea.description }}</p>
        {% if tea.age > 0 %}
        <p>Age: {{ tea.age }}</p>
        {% else %}
        <p>Age: Unopened</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'teas_update' tea.id %}">Edit</a>
        <a href="{% url 'teas_delete' tea.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_sweetening' tea.id %}" method="post">
      {% csrf_token %} {{ sweetening_form.as_p }}
      <input type="submit" class="btn" value="Add Sweetening" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Style</th>
        </tr>
      </thead>
      <tbody>
        {% for sweetening in tea.sweetening_set.all %}
        <tr>
          <td>{{sweetening.date}}</td>
          <td>{{sweetening.get_style_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ tea.name }}'s cups</h3>
    {% if tea.cups.count %} {% for cup in tea.cups.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color: {{ cup.color }}">{{ cup.color }}</span> {{
          cup.name }}
        </span>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No cups :(</h5>
    {% endif %}
  </div>
  <!-- Available cups will come after this line -->
</div>
<div class="col s6">
  <h3>Available cups</h3>
  {% if cups.count %} {% for cup in cups.all %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">
        A <span style="color: {{ cup.color }}">{{ cup.color }}</span>
        {{cup.name }}
      </span>
    </div>
    <div class="card-action">
      <form action="{% url 'assoc_cup' tea.id cup.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn">Add</button>
      </form>
    </div>
  </div>
  {% endfor %} {% else %}
  <h5>{{cat.name}} Already Has All Cups Available</h5>
  {% endif %}
</div>
<script>
  // date picker
  var dateEl = document.getElementById("id_date");
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  // dropdown for style(sweetening)
  var selectEl = document.getElementById("id_style");
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/teas/index.html
{% extends 'base.html' %} {% block content %}

<h1>Tea List</h1>

{% for tea in teas %}
<div class="card">
  <a href="{% url 'detail' tea.id %}">
    <div class="card-content">
      <span class="card-title">{{ tea.name }}</span>
      <p>Kind: {{ tea.kind }}</p>
      <p>Description: {{ tea.description }}</p>
      {% if tea.age > 0 %}
      <p>Age: {{ tea.age }} months old</p>
      {% else %}
      <p>Age: Unopened</p>
      {% endif %}
    </div>
  </a>
</div>
{% endfor %} {% endblock %}